[WEBSITE-890] Initial implementation of multi_direction_sort
ukparliament/parliament-ntriple pull request #3
Opened 2017-05-11 12:11 UTC by katylouise

2017-05-11 12:40 UTC, mattrayner requested changes

2017-05-11 12:40 UTC, mattrayner commented on lib/parliament/ntriple/utils.rb
> +
remove this 😛

2017-05-11 12:40 UTC, mattrayner commented on lib/parliament/ntriple/utils.rb
> +      def self.multi_direction_sort(args)
Can we add some documentation to this including examples?

2017-05-11 12:40 UTC, mattrayner commented on lib/parliament/ntriple/utils.rb
> +        list.sort! do |obj1, obj2|
We need to look at the efficiency of this algorithm - do we understand the potential complexity?

2017-05-11 12:40 UTC, mattrayner commented on lib/parliament/response/ntriple_response.rb
> +      def multi_direction_sort(parameters)
Documentation including examples is also required here

2017-05-11 12:40 UTC, mattrayner commented on spec/parliament/ntriple/utils_spec.rb
> +    it 'returns a response sorted by member_count (desc) and name (asc)' do
We need to add tests for (asc), (asc) - (desc), (desc) + what if you provide more that two?

2017-05-11 12:40 UTC, mattrayner commented on spec/parliament/response/ntriple_response_spec.rb
> +  describe '#multi_direction_sort' do
See above

2017-05-12 14:49 UTC, katylouise commented on spec/parliament/ntriple/utils_spec.rb
> +    it 'returns a response sorted by member_count (desc) and name (asc)' do
Done - there are now tests for asc asc, desc desc, desc asc and three parameters.

2017-05-15 11:55 UTC, mattrayner commented on spec/parliament/ntriple/utils_spec.rb
> +    it 'returns a response sorted by member_count (desc) and name (asc)' do
Just to check - is there an upper limit to the number of sorts and orders you will allow?

If so we should raise an error if more than that - if not we should document and maybe have like a 10 deep test for sanity checking

2017-05-15 11:57 UTC, mattrayner requested changes
See comment relating to upper limit of multi_order sort

2017-05-15 12:38 UTC, katylouise commented on spec/parliament/ntriple/utils_spec.rb
> +    it 'returns a response sorted by member_count (desc) and name (asc)' do
Done - there is now an extra test for 5 sort parameters

2017-05-17 09:58 UTC, mattrayner approved these changes

2017-05-17 09:59 UTC, merged